### ISSUE TITLE
Incorrect pagination behaviour when using the library in Electron (Specifically renderer process) 

### ISSUE THREAD

**Issue by alaincao** [jdalrymple/gitbeaker#385] opened 2019-07-08 18:43 UTC
**Description**

I am currently trying to upgrade a project from v4.2.7 (which is **still** working fine with this version today) to v8.0.0 (and now v9.0.0) and I have problems with pagination.  
I am obviously doing something wrong, but I really can't see what ...  

I noticed that the default behaviour for all `api.XXX.all()` with no parameter now is to returns only 20 rows. That seem to contradict what's been said in #94, first comment: *"We changed it in the past to not just return 30 results since it was misleading. 30 != all lol"* **and** the documentation in `Readme.md`: [*"For any .all() function on a resource, it will return all the items from Gitlab"*](https://github.com/jdalrymple/node-gitlab/tree/862768a4f3cb6c0008969926551205d969e619f1#pagination).  

Ok, but now the strange thing is if I add `{ showPagination:true }` in the requests, all the pagination info I get are invariably `undefined`.
This happens with whatever parameters I put in as parameters (page/perPage/etc.).  
Also, `perPage` seem to be respected, but I can't get more than 100 rows returned. There seem to be a max somewhere.

**Steps to reproduce / Actual behaviour**
![image](https://user-images.githubusercontent.com/2505008/60832886-4fba2180-a1bd-11e9-826b-17f7badcc894.png)

**Expected behaviour**
`.all()` should return all rows.

**Possible fixes**
Sorry, 'can't help here ...

**Comment by alaincao** [comment] 2019-07-08 18:52
Hint:  
if I HTTP GET directly at `/api/v4/projects/8/pipelines`, I get 20 rows.  
and if I do `/api/v4/projects/8/pipelines?per_page=110`, I get 100 rows ...

**Comment by jdalrymple** [comment] 2019-07-08 19:27
That is very very odd. Ill give it a look soonish, hopefully its something small!

**Comment by jdalrymple** [comment] 2019-07-09 14:17
You used the code you specified above?

![image](https://user-images.githubusercontent.com/3743662/60895420-a3b31d80-a232-11e9-9cc4-80e941b53a47.png)

If you wanted all results, why specify the page? Though even if you did, the rest of the pagination information should be there. Anyways looking into it now!

**Comment by alaincao** [comment] 2019-07-09 15:57
That was just test. With or without, it did not change the `undefined` values.

**Comment by jdalrymple** [comment] 2019-07-12 17:03
So i tested the pagination with labels and it seems to work. Ill check pipelines directly and see if anything sticks out there :(

**Comment by jdalrymple** [comment] 2019-07-12 19:47
If you get the chance, could you check that you get the same results when getting all the labels through the labels api

**Comment by alaincao** [comment] 2019-07-13 19:05
First: sorry I could not do this earlier, but I could not afford to lose more time on this at work ...

I made some tests to isolate the problem, and when I run the code from the CLI, it works as expected.  
But I tend to first develop my modules using Electron, and from there, I have the problematic results above: 'all()' returns 20 lines and 'showPagination:true' is not working.

So it seems Electron is the cause of the problem here ; I suppose this issue can be closed to open a more general one "Does not work in Electron", but I have to admit I ended up using direct HTTP calls to the API, so I'm out.  

nb: I think the download of artifacts is problematic too, btw.

Big thanks for that project anyway!

**Comment by jdalrymple** [comment] 2019-07-15 12:44
No worries! I appreciate the extra investigation :)

**Comment by Helam24** [comment] 2019-07-15 19:08
I'm also having problems in Electron. Only getting 20 results from the `.all` calls for everything I'm using (Branches, MergeRequests).

**Comment by Helam24** [comment] 2019-07-15 20:16
@alaincao @jdalrymple Just found that it does work properly if the api calls are done on the main electron process, and not the renderer process (how-to on this demonstrated here https://ourcodeworld.com/articles/read/537/how-to-execute-a-function-of-the-main-process-inside-the-renderer-process-in-electron-framework).

Would be nice if it worked either way though.

**Comment by jdalrymple** [comment] 2019-07-16 14:32
I wonder what would make the difference :/

**Comment by jdalrymple** [comment] 2020-04-25 10:23
Does the problem still occur? @Helam24

**Comment by Helam24** [comment] 2020-04-29 17:52
@jdalrymple I’m not sure. I’m not working on that project at the moment. I ended up moving all the relevant calls to the main process instead of the renderer process which is probably better anyway, just a little more work. Were changes made that might’ve fixed the issue?

**Comment by jdalrymple** [comment] 2020-04-29 17:55
Nothing specific, though since then we've released a browser specific version and cleaned up alot of the logic.

**Comment by jdalrymple** [comment] 2020-06-16 12:12
Closing for the time being. I'll reopen if the problem is encountered again!

**Closed by jdalrymple** 2020-06-16 12:12 UTC
Labels: bug
