### ISSUE TITLE
@gitbeaker/node library clashes with cloudflare library

### ISSUE THREAD

**Issue by hanselke** [jdalrymple/gitbeaker#977] opened 2020-07-14 07:04 UTC
Whenever you import cloudflare's lib , the gitlab service will hit 127.0.0.1 instead of host. 
Probably due to both cloudflare and gitbeaker/node using the got request lib. Not sure which library is the one that is misconfigured.

`const { Gitlab } = require('@gitbeaker/node')
const cf = require('cloudflare')({});
const serviceTEST = new Gitlab({
    "host": "https://git.activ.ltd",
    "token": "TESTTOKEN"

})

serviceTEST.Users.show(1).then((res) => {
    console.log("test res",res)
}).catch((err) => {
    console.error('test err',err)
})
`

test err RequestError: connect ECONNREFUSED 127.0.0.1:443

without requiring cloudflare, it works as expected.

**Comment by jdalrymple** [comment] 2020-07-17 10:36
Weird, maybe the got library is tracking state? Not really sure :/ Would have to dig into this one

**Comment by nicklasfrahm** [comment] 2020-09-12 09:49
I am having the same issue without the cloudflare library.

**Comment by jdalrymple** [comment] 2020-09-12 11:05
Sorry for the delay, still trying to fix #1112

**Comment by yaronya** [comment] 2021-01-18 12:50
> I am having the same issue without the cloudflare library.
Yes, this issue is regardless of the `cloudflare` library. In fact, it might clash with any other library that imports `got`. Unfortunately, I couldn't overcome this issue so I had to stop using `@gitbeaker/node` 😢

**Comment by jdalrymple** [comment] 2021-01-18 15:18
> > I am having the same issue without the cloudflare library.
> 
> Yes, this issue is regardless of the `cloudflare` library. In fact, it might clash with any other library that imports `got`. Unfortunately, I couldn't overcome this issue so I had to stop using `@gitbeaker/node` cry

Any chance you could throw up a test repo with this behaviour? Could help in narrowing down where the problem is coming from

**Comment by yaronya** [comment] 2021-01-18 17:14
> Any chance you could throw up a test repo with this behaviour? Could help in narrowing down where the problem is coming from

Hi @jdalrymple 
TBH I tried to reproduce it but couldn't find the root cause. I'm using a robust monorepo so it's kind hard to track which dependency has screwed up the `got` client. 
I'm not even sure I have the same issue, but the error is the same (`connect ECONNREFUSED 127.0.0.1:443`).

If I'll find any other clue I wouldn't hesitate to share it with you 🙏

**Comment by mkkeffeler** [comment] 2021-02-15 21:30
man, same thing here. was importing ```got``` and getting

```
(node:16841) UnhandledPromiseRejectionWarning: RequestError: connect ECONNREFUSED 127.0.0.1:443
    at ClientRequest.<anonymous>
```

not sure i can use gitbeaker for this use case now either...

**Comment by jdalrymple** [comment] 2021-02-15 21:38
Thats super weird. Still not sure whats going on there and havent had the time to dig really deep into it. Any chance @mkkeffeler  you could throw together a test repo with this behaviour?

**Comment by linuxbandit** [comment] 2021-04-01 15:50
can confirm the issue is there without cloudflare library

**Comment by jdalrymple** [comment] 2021-04-04 00:51
@linuxbandit hmm can you provide a bit more information about your setup or even how you produced the error. Might help in narrowing down the problem

**Comment by janpansa** [comment] 2021-05-01 15:02
Seems like I have the same issue. I am using cloudflare and gitlab on the same project.  I am getting the following error:

```
{"name":"RequestError","code":"ECONNREFUSED","timings":{"start":1619880262758,"socket":1619880262760,"lookup":1619880262761,"upload":1619880262761,"error":1619880262761,"phases":{"wait":2,"dns":1,"request":null,"total":3}}} 
```

I initialise my gitlab object like so:

```
const { Gitlab } = require('@gitbeaker/node');

const api = new Gitlab({
  token: 'I_ADD_MY_TOKEN_HERE',
})

I am using gitlab.com and have added all  permissions to my token without any luck.

**Comment by jdalrymple** [comment] 2021-05-02 01:10
Yea there definitely seems to be a conflict internally but i cant need to narrow it down consistently. Im guessing its related to got in some fashion. @janpansa Any chance you could throw together a sample repo where you can replicate the issue ?

**Comment by jdalrymple** [comment] 2022-02-04 23:56
Im going to close this for now, if anyone has the time to throw together a test repo with the consistent behaviour, ill dig back into this,

**Closed by jdalrymple** 2022-02-04 23:56 UTC
Labels: bug, scope:node
